
name: test7

on:
  push:
    branches: [ '*' ]
  workflow_dispatch:
    inputs:
      environment:
        description: "部署的环境"
        required: true
        default: "staging"
      version:
        description: "版本号"
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no peibozhao@101.42.48.206 "cd /tmp/ && echo hello > test.txt"

