name: test
on:
  push:
    branches:
      - master
jobs:
  first_job:
    name: 'first job'
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: checkout@master
    - name: pwd
      run: pwd
    - name: ls
      run: ls
    - name: cat
      run: cat test.cpp
  second:
    name: '2 job'
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo run first job $TEST_PATH
      env:
        TEST_PATH: test_path
    - name: echo2
      run: echo run second job $TEST_PATH
      env:
        TEST_PATH: test_path
    - name: echo3
      run: echo run third job $TEST_PATH
      env:
        TEST_PATH: test_path

