name: Build and Dockerize C++ App

on:
  workflow_dispatch:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Compile C++ Code
        run: |
          g++ test.cpp -o mytest_exec
          md5sum mytest_exec

      - name: Upload Compiled App
        uses: actions/upload-artifact@v4
        with:
          name: compiled-app
          path: mytest_exec

      - name: Create release
        run: gh release create v1.0.0 mytest_exec --title "Release v1.0.0" --notes "Release notes for v1.0.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dockerize:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Compiled App
        uses: actions/download-artifact@v4
        with:
          name: compiled-app
          path: .

      - name: docker test
        id: docker_test
        uses: docker/metadata-action@master
        with:
          images: abc/def

      - name: Test run
        run: |
          md5sum mytest_exec
          chmod +x mytest_exec
          ./mytest_exec
          echo "hello ${{ github.actor }}"
          echo "hello ${{ steps.docker_test.outputs.tags }}"
          echo "hello ${{ steps.docker_test.outputs.labels }}"


      # - name: Build Docker Image
      #   run: docker build -t myuser/cpp-app:${{ github.sha }} .

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Push Image
      #   run: docker push myuser/cpp-app:${{ github.sha }}

