
name: test7

on:
  push:
    branches: [ '*' ]
  workflow_dispatch:
    inputs:
      environment:
        description: "部署的环境"
        required: true
        default: "staging"
      version:
        description: "版本号"
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: testenv
      url: http://101.42.48.206:80
    steps:
      - name: 打印输入参数
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"
