name: test
on:
  push:
    branches:
      - master
jobs:
  first_job:
    name: 'first job'
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo run first job $TEST_PATH
      env:
        TEST_PATH: test_path
    - name: echo2
      run: echo2 run first job $TEST_PATH
      env:
        TEST_PATH: test_path
