# .github/workflows/build.yml
name: Build Project

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Compile C++ Code
        run: |
          g++ test.cpp -o mytest_exec
          md5sum mytest_exec
      - name: Upload Compiled App
        uses: actions/upload-artifact@v4
        with:
          name: compiled-app
          path: mytest_exec

