
name: test7

on:
  push:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          echo '${{ toJson(github) }}'

