name: test2
on:
  push:
    branches:
      - master
jobs:
  first_job:
    name: install docker
    runs-on: ubuntu-latest
    steps:
    - name: apt update
      run: apt update
    - name: install
      run: apt install apt-transport-https ca-certificates curl software-properties-common
    - run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - name: cat
      run: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    - name: update
      run: apt update
    - name: prepare
      run: apt-cache policy docker-ce
    - name: install
      run: apt install docker-ce
    - name: status
      run: systemctl status docker
